name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # Se ejecuta al hacer push en main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login a Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construir y publicar la imagen
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: eliasroy/medilink-frontend:latest
